<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Context\" />
    <Folder Include="Settings\" />
    <Folder Include="Repositories\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\CineCloud.Queries.Application\CineCloud.Queries.Application.csproj" />
  </ItemGroup>

</Project>
